export const layoutsTheme = {
  colorsTheme: {
    standart: {
      colorBtn: "#4E71FE",
      colorTextBtn: "#FFFFFF",
      colorTextP: "#ABB3BA",
      colorTextH: "#000000",
      colorShadow: "#0000001A",
      colorHoverShadow: "#5d73ca",
      colorBack: "#FFFFFF",
    },
    balanced: {
      colorBtn: "#990534",
      colorTextBtn: "#e27d60",
      colorTextP: "#914d20",
      colorTextH: "#e27d60",
      colorShadow: "#990534",
      colorHoverShadow: "#00ffdd",
      colorBack: "#5ec2b5",
    },
    easyDay: {
      colorBtn: "#68b0ab",
      colorTextBtn: "#ffffff",
      colorTextP: "#4d4d4d",
      colorTextH: "#2e2e2e",
      colorShadow: "#49988c",
      colorHoverShadow: "#407e7a",
      colorBack: "#eaf2f1",
    },
    strict: {
      colorBtn: "#4e71fe",
      colorTextBtn: "#ffffff",
      colorTextP: "#4a4a4a",
      colorTextH: "#2b2b2b",
      colorShadow: "#3b5998",
      colorHoverShadow: "#2b3e8c",
      colorBack: "#f2f4f6",
    },
    reddish: {
      colorBtn: "#ff6f61",
      colorTextBtn: "#ffffff",
      colorTextP: "#595959",
      colorTextH: "#333333",
      colorShadow: "#d64a3b",
      colorHoverShadow: "#b44335",
      colorBack: "#ffefec",
    },
    grayWorld: {
      colorBtn: "#7e7c7a",
      colorTextBtn: "#ffffff",
      colorTextP: "#444444",
      colorTextH: "#1c1c1c",
      colorShadow: "#5e5d5b",
      colorHoverShadow: "#3e3d3b",
      colorBack: "#f7f7f7",
    },
    drakula: {
      colorBtn: "#f9a602",
      colorTextBtn: "#ffffff",
      colorTextP: "#5a5a5a",
      colorTextH: "#2d2d2d",
      colorShadow: "#d48802",
      colorHoverShadow: "#b37802",
      colorBack: "#fff6e5",
    },
  },
  media: {
    laptop: "screen and (min-width: 1001px) and (max-width: 1250px)",
    tablet: "screen and (min-width: 651px) and (max-width: 1000px)",
    mobile: "screen and (max-width: 650px)",
  },
};
